# Generated by Django 4.1.4 on 2023-02-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ed_level',
            name='level',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ed_major',
            name='major',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='level',
            field=models.CharField(choices=[('Entry', 'Entry'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Expert', 'Expert')], max_length=30),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_staffing.expertise')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_staffing.field')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_staffing.education')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_staffing.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=10)),
                ('educations', models.ManyToManyField(to='manage_staffing.education')),
                ('skills', models.ManyToManyField(to='manage_staffing.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_staffing.employer')),
                ('requirements', models.ManyToManyField(to='manage_staffing.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_staffing.classification'),
        ),
        migrations.AddField(
            model_name='education',
            name='ed_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_staffing.ed_level'),
        ),
        migrations.AddField(
            model_name='education',
            name='ed_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_staffing.ed_major'),
        ),
    ]
